### ISSUE TITLE
post_migrate_handler

### ISSUE THREAD

**Issue by zN3utr4l** [fabiocaccamo/django-admin-interface#208]
**Python version**
3.8

**Django version**
3.2.16

**Package version**
0.22.2

**Current behavior (bug description)**
The current behavior of the post-migration signal (post_migrate_handler) does not take into account any routing of the databases

```
from django.conf import settings


class DatabaseAppsRouter(object):
    """

        arouter to control all database operations on models for different
        databases.

        in case an app is not set in settings.DATABASE_APPS_MAPPING, the router
        will fallback to the `default` database.

        Settings example:

        DATABASE_APPS_MAPPING = {'app1': 'db1', 'app2': 'db2'}
    """

    def db_for_read(self, model, **hints):
        """Point all read operations to the specific database"""
        if model._meta.app_label in settings.DATABASE_APPS_MAPPING:
            return settings.DATABASE_APPS_MAPPING[model._meta.app_label]

        return None

    def db_for_write(self, model, **hints):
        """Point all write operations to the specific database"""
        if model._meta.app_label in settings.DATABASE_APPS_MAPPING:
            return settings.DATABASE_APPS_MAPPING[model._meta.app_label]

        return None

    def allow_relation(self, obj1, obj2, **hints):
        """Allow any relation between apps that use the same database"""
        db1 = settings.DATABASE_APPS_MAPPING[obj1._meta.app_label]
        db2 = settings.DATABASE_APPS_MAPPING[obj2._meta.app_label]

        if db1 and db2:
            return db1 == db2

        return None

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        """Make sure that apps only appear in the related database"""

        if db in settings.DATABASE_APPS_MAPPING.values():
            return settings.DATABASE_APPS_MAPPING[app_label] == db

        elif app_label in settings.DATABASE_APPS_MAPPING:
            return False

        return None
```

```

DATABASES = {
    'default': {
        'ENGINE': 'timescale.db.backends.postgresql',
        'NAME': TIMESCALE_DB_HOST_FORMATTED['Database'],
        'USER': TIMESCALE_DB_HOST_FORMATTED['Username'],
        'PASSWORD': TIMESCALE_DB_HOST_FORMATTED['Password'],
        'HOST': TIMESCALE_DB_HOST_FORMATTED['Host'],
        'PORT': TIMESCALE_DB_PORT,
        'OPTIONS': {
            'client_encoding': 'UTF8',
            # 'isolation_level': psycopg2.extensions.ISOLATION_LEVEL_SERIALIZABLE,
        }
    },
    'collector': {
        'ENGINE': 'djongo',
        'NAME': 'Database',
        'ENFORCE_SCHEMA': True,
        'CLIENT': {
            'host': MONGO_DB_HOST
        }
    }
}


DATABASE_APPS_MAPPING = {
    'contenttypes': 'default',
    'auth': 'default',
    'admin': 'default',
    'django_cache': 'default',
    'sessions': 'default',
    'staticfiles': 'default',
    'admin_interface': 'default',
    'collector': 'djongo(mongodb)',
    'main': 'default',
}

DATABASE_ROUTERS = ['routers.DatabaseAppsRouter']
```

**Workaround**
```
def apply_theme(sender, **kwargs):
    from django.conf import settings
    from admin_interface.models import Theme
    from admin_interface.cache import del_cached_active_theme

    del_cached_active_theme()
    theme = Theme.get_active_theme('default')
    theme.logo = ....
    theme.favicon = ....
    theme.save()


class MainConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'main'
    verbose_name = 'analyser configuration'

    def ready(self) -> None:
        from admin_interface.models import Theme

        Theme.post_migrate_handler = apply_theme
        if 'admin_interface_theme' in connection.introspection.table_names():
            apply_theme(None)
```

**Comment by fabiocaccamo** [comment]
@zN3utr4l you are not passing **kwargs to `apply_theme` function, it does nothing because it doesn't enter the condition.

Could you provide a failing test please?

**Comment by zN3utr4l** [comment]
if I don't override your post migrate function it fails.

Try to copy my routing class and create 2 databases in django, I think it's ok they are on the same system too (postgresql) and in the routing dictionary you put two projects, yours with routing on default and another one with routing on default2, you run python manage.py migrate --database default and python manage.py migrate --database default2 and in the second call it should go wrong because you try to do in your function .using('database2') but the migrations of your project they are on default.

**Comment by fabiocaccamo** [comment]
@zN3utr4l does this worked correctly for you with the `0.22.1` version?

**Comment by zN3utr4l** [comment]
yes, because there was no .using(db) and the queries were addressed by themselves via my file routing

**Comment by fabiocaccamo** [comment]
@zN3utr4l I understand. If you can submit a PR with a failing test that should succeed I will fix it and publish a new release quickly.

**Comment by zN3utr4l** [comment]
At the moment I can't, overriding your function seems to work for now

**Comment by fabiocaccamo** [comment]
@VaZark have you the time to add a test for this issue?

**Comment by VaZark** [comment]
I think we set the database=None, we can be backward-compatible . I'll add a test too

```python
    def get_active_theme(database=None):
        objs_manager = Theme.objects if database is none else Theme.objects.using(database)
```

**Comment by VaZark** [comment]
@fabiocaccamo do you know any examples or resources with testing with a DB Router ?? I'm unable to find much about it.

**Comment by fabiocaccamo** [comment]
@VaZark there is a good example at the top of this issue.

**Comment by zN3utr4l** [comment]
![image](https://user-images.githubusercontent.com/73225008/203492141-d61c2235-1ccd-471e-be90-1010864ea65d.png)
using this piece of code, `using = using or router.db_for_write(self.__class__, instance=self)`
taken from from django.db.models.Model

**Comment by fabiocaccamo** [comment]
Fix available with `0.23.0` version.

**Comment by zN3utr4l** [comment]
I think the problem is not solved because in post migrate `db = kwargs["using"]` is used, it still gives me an error

**Comment by VaZark** [comment]
@zN3utr4l can u post the the value in kwargs you get in the `post_migrate_handler`  please ? And if you can, the kwargs from the delete and the pre_save handlers would be appreciated as well.

**Comment by zN3utr4l** [comment]
**Command**:
`python manage.py migrate main --database default`

**kwargs migrate func**:
`{'signal': <django.dispatch.dispatcher.Signal object at 0x000002349660B790>, 'app_config': <MainConfig: main>, 'verbosity': 1, 'interactive': True, 'using': 'default', 'apps': <django.db.migrations.state.StateApps object at 0x00000234AAABE220>, 'plan': []}`

**Command**:
`python manage.py migrate main --database collector`

**kwargs migrate func**:
`{'signal': <django.dispatch.dispatcher.Signal object at 0x000002349660B790>, 'app_config': <MainConfig: main>, 'verbosity': 1, 'interactive': True, 'using': 'collector', 'apps': <django.db.migrations.state.StateApps object at 0x00000234AAABE220>, 'plan': []}`

**Comment by zN3utr4l** [comment]
look at this 
https://docs.djangoproject.com/en/3.2/ref/signals/

**Comment by VaZark** [comment]
`using` is an expected param in all signals and from the output you've posted, I can see that `using` is being properly sent. So everything is fine on paper but there obviously seems to be an issue.

So, can you provide us with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please?

**Comment by VaZark** [comment]
The issue seems to be the migration for the collector DB invokes admin_interface  even though `allow_migrate` should return _False_ and prevent the migration from running. 

Can you take a look at your allow_migrate setup please ?

**Comment by zN3utr4l** [comment]
the problem is not allow migration, it works fine as the admin_interface table is not created on the collector db but on the default db.

**Comment by zN3utr4l** [comment]
Look: for 

https://docs.djangoproject.com/en/4.1/topics/db/multi-db/#selecting-a-database-for-save

**Comment by fabiocaccamo** [comment]
@zN3utr4l could you submit a PR with a minimal failing test that should succeed?

**Comment by zN3utr4l** [comment]
your tests in test_multidb not work?

**Comment by VaZark** [comment]
Here in the [docs](https://docs.djangoproject.com/en/3.2/ref/signals/#post-migrate) , it clearly states that's post_migrate is run even if migrations do not apply to the app. That's what been tripping me up. 

@zN3utr4l  can you try just commenting out the `post_migrate_handler`  and the it's reference in the `app.py` please ? 

@fabiocaccamo I found the root cause. Do you have any alternate ideas to create a default theme ? The test run fine without it.

**Comment by zN3utr4l** [comment]
sorry for not saying before that's post_migrate is run even if migrations do not apply to the app.
for now I have overridden the post migrate as you see in the Workaround section of the first comment

**Comment by fabiocaccamo** [comment]
@VaZark frankly I don't remember why I added it to the `post_migrate_handler`, but surely to avoid some error, I'm sorry. 
Lesson learnt: I should have left a comment for the my self  of the future. :)

**Comment by VaZark** [comment]
I’m pretty sure it’s to create the default theme on installation. The function is called in the appConfig. Maybe we can just migrate that function directly to appconfig and remove the signal?

**Comment by zN3utr4l** [comment]
but how is this supposed to solve the error created by using? in the new function Theme.objects should not have using

**Comment by VaZark** [comment]
Because the code will not be called at all when u migrate using ‘using’ 

The error comes only on post-migrate. We use ‘using’ in the pre-save, post-save too. If using was actually the root error, those functions would’ve throw an error before post-migrate

**Comment by fabiocaccamo** [comment]
@VaZark yes, it's just for creating the default theme, but I don't remember what happened without the `post_migrate_handler`.

Maybe there is an error when installing the library on a new project, should test that.

**Comment by fabiocaccamo** [comment]
I added it here:
https://github.com/fabiocaccamo/django-admin-interface/commit/d2846b742071e3d413cf9e460a21a0037737b93f

**Comment by VaZark** [comment]
You were probably inspired by this answer to consistently insert data after all migrations : https://stackoverflow.com/a/40238464/6052586

Coz I'm stuck on how to mark a migration as the last to run to not break tests and not meddle with migration history for any future changes

**Comment by fabiocaccamo** [comment]
@VaZark mhmh no... I would have voted it.

**Comment by fabiocaccamo** [comment]
Fixed in 60649ac4e6c11c3d7d0f340085db0d2ada080752
